-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg19+ic647Xt+r+jRk
e2cfLaEROeaSsMNqnHbTHMELE5mgCgYIKoZIzj0DAQehRANCAARK7nPrVZ1aUhfF
ycqDTlENbXYeVDQK1CM0+560gQUnWVrG7REfvicEp+UWRQh/mhxmLULUZSk2JXf2
jqG9ChJf
-----END PRIVATE KEY-----